config/routes.rb
SharedTodoApp::Application.routes.draw do
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	include TodosHelper

  def new
	  @todo = Todo.new
  end

  def index
  	@todos = Todo.all
  	render :index
  end

  def show
  	@todo = Todo.find(params[:id])
  end

  def delete
  	@last = Todo.last
  	@last.delete
  	redirect_to action: 'index'
  end

  def create
  	@todo = Todo.new(todo_params)
  	@todo.save
  	redirect_to todo_path(@todo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
	def todo_params
		params.require(:todo).permit(:todo_item)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharedTodoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="row">
        <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
            <span class="sr-only">TOGGLE NAVIGATION</span>
            <span class="mymenu">Menu</span>
            </button>
            </div>
            <div class="collapse navbar-collapse" id="collapse">
            	<ul class="nav navbar-nav">
                	<li><a href="#">Holder</a></li>
                	
                	<li class="active"><a href="#">Todos</a></li>
                	 
                </ul>  
            </div>
        </nav>
    </div>
<%= yield %>

</body>
</html>

app/views/todos/delete.html.erb
<p>Todo successfully deleted</p>
<a href="/todos/index">Back</a>

app/views/todos/index.html.erb
<title>Shared Todo App </title>
<div class="container">
	<h1>Shared Todo App</h1>

	<div class="row">
		<div class="col-lg-8">
			<h4>All your todos here</h4>
				<ul class="list-group">
					<% @todos.each do |t| %>
					<li class="list-group-item"> <span class="badge">Incomplete</span> <%= t.todo_item %> </li>
					<% end %>
				</ul>
		</div>
		<div class="col-lg-4">
		<p>
		<%= link_to 'Create a new task', new_todo_path %>
		</p>
		</div>
	</div>
	</div>
</div>

app/views/todos/new.html.erb
<div class="col-lg-4">
		<h4>Add a new task</h4>
			<div class="form-group">
		  		<%= form_for(@todo) do |f| %>
		  		<p>
		  		<%= f.label :todo_item %><br>
        		<%= f.text_field :todo_item %>
        		</p>
        		<p>
		  		<%= f.submit %>
		  		</p>
				<% end %>
			</div>
				<p>
		<%= link_to 'Back to List', todo_path(@todo) %>
		</p>
		</div>

app/views/todos/show.html.erb
<div class = "row">
	<div class="col-lg-8">
		<div class="panel panel-default">
			<article>
				<p class="panel-body"><%= @todo.todo_item %></p>
			</article>
		</div>
			<%= link_to "Back to List", todos_path %>
	</div>

</div>